### ISSUE TITLE
Release 1.18.0

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/delivery-console#1092]
Welcome Release Captain! ⛵️ 

- [x] Assign this issue to yourself
- [x] Create 1.19.0 Milestone (due date two weeks from now)
- [x] Move all open tickets in 1.18.0 to 1.19.0
- [x] Close 1.18.0 Milestone
- [x] Pull master
- [x] Ensure `yarn test` passes
- [x] `git tag v1.18.0; git push --tags`
- [x] `@here deploying delivery-console to stage v1.18.0 https://github.com/mozilla/delivery-console/milestone/7?closed=1` in #normandy
- [x] Quickly verify that stage loads with v1.18.0
- [x] Request ops to deploy in #normandy
- [x] Verify that prod loads with v1.18.0
- [x] Approve and merge all open dependabot PRs
- [x] Create release issue for Release v1.19.0

**Comment by rehandalal** [comment]
Tag did not get deployed to stage.
