### ISSUE TITLE
Preference rollout sends all values as strings

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/delivery-console#1122]
It looks to me from playing with the delivery console preference rollout UI that regardless of what preference type is selected from the drop down, it sends everything as a string:

```
mythmon 6:04 PM
i guess we've never launched a rollout with the UI yet
jkerim 6:05 PM
you used edi before?
mythmon 6:05 PM
I was thinking "oh, we've done rollouts before, this can't be broken"
no, I used DC's JSON text field
jkerim 6:05 PM
oh i see
where you would write
{"preferenceName": "thing", "value": true}
or
{"preferenceName": "thing", "value": "true"}
which are different things
which means that if dc is generating "preferences":[{"preferenceName":"browser.newtabpage.activity-stream.enabled","value":"true"}] for the boolean case
that's incorrect
right?
you would expect the dc output to be "preferences":[{"preferenceName":"browser.newtabpage.activity-stream.enabled","value": true}] if the type was boolean
and "preferences":[{"preferenceName":"browser.newtabpage.activity-stream.enabled","value":"true"}] if the type was string?
mythmon 6:30 PM
@jkerim yes, that's all correct
```

**Comment by rehandalal** [comment]
there are two issues here:
- experimenter is sending the wrong data types which led to the initial value always being set to a string on import
- DC's interface does not cast the data to the new type when changing types so unless the user updates the value it will get saved incorrectly

**Comment by jaredlockhart** [comment]
I updated the experimenter side to send the correct json type in https://github.com/mozilla/experimenter/commit/6b1e77505261b1083b7dc1998ed4799da6d7a30a

@rehandalal Not sure if you'd also like to do anything on the dc side?
