### ISSUE TITLE
Pagination is broken after a certain page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#1136]
**[Affected versions]:**
- Firefox Nightly 83.0a1, Build ID 20201006161706

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net/recipe/.
2. Go to the 45th page.
3. Scroll down the page and click the 46th page button.
4. Observe the behavior.

**[Expected results]:**
- The 46th page contents is displayed.

**[Actual results]:**
- The same content is loaded.

**[Notes]:**
- The issue is also reproducible after searching for a keyword.
- It looks like there are less pages than what is currently available in the UI (111), so after a certain page the same content is shown.
- Attached a screen recording of the issue.
![pagination not working after page 45](https://user-images.githubusercontent.com/18304511/95339108-5c479100-08bc-11eb-97d2-6b310c68a5b9.gif)

**Comment by mythmon** [comment]
We aren't working on Delivery Console anymore, and plan to shut it off soon. Any workflows that use it should migrate to [Normandy Devtools](https://github.com/mozilla-extensions/normandy-devtools). Any workflows that aren't already supported by NDT should be filed as issues on that repo.
