### ISSUE TITLE
Searching for a term does not do anything if performed on the 3rd page of recipes and on

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#1137]
**[Affected versions]:**
- Firefox Nightly 83.0a1, Build ID 20201006161706

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net/recipe/.
2. Go to the 2nd page.
3. Search for a term (eg. `cmuresan`) and observe the behavior.

**[Expected results]:**
- Recipes with that keyword are displayed.

**[Actual results]:**
- The same content is loaded.

**[Notes]:**
- The issue is also reproducible after searching for a keyword.
- The issue is NOT reproducible on the 1st and 2nd pages.
- Attached a screen recording of the issue: [Link](https://drive.google.com/file/d/1ZM9KTtK4obR2y9zMTRhBbsCWbJfmobCx/view?usp=sharing)

**Comment by mythmon** [comment]
We aren't working on Delivery Console anymore, and plan to shut it off soon. Any workflows that use it should migrate to [Normandy Devtools](https://github.com/mozilla-extensions/normandy-devtools). Any workflows that aren't already supported by NDT should be filed as issues on that repo.
