### ISSUE TITLE
[Enhancement] Consider removing old actions if they are currently not in use

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#1138]
We should consider removing the `preference-experiment`, `opt-out-study`, and `addon-study` actions if they are not used currently, or there is no plan for them to be used in the future.

I realize that we keep them around for the possibility of an experiment needed on a version of Firefox that does not support the newer actions, but the newer versions of the actions were implemented over ~10 versions ago. Do we still think we will use the old actions in the future?

**Comment by mythmon** [comment]
We aren't working on Delivery Console anymore, and plan to shut it off soon. Any workflows that use it should migrate to [Normandy Devtools](https://github.com/mozilla-extensions/normandy-devtools). Any workflows that aren't already supported by NDT should be filed as issues on that repo.

As a side note, parts of the NDT UI show the list of actions grouped by type, with the mentioned types listed as "Legacy".
