### ISSUE TITLE
antd "whole package usage" warnings when running the tests

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#150]
When running the tests, a lot of the following warnings are displayed:

```
You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size
```

I've tried literally everything I could think about to fix this issue, but haven't managed to. I believe it's because jest doesn't use webpack, and thus doesn't use `config-overrides.js` (see https://github.com/timarney/react-app-rewired#extended-configuration-options), which injects the `babel-import-plugin` that should fix this).
I tried:
- using the method from the link above to have Jest use the config-overrides (but there's an error when trying to inject the plugin, some keys are missing from the `config`)
- adding a `babel` entry in the package.json
```json
  "babel": {
    "plugins": [["import", { "libraryName": "antd", "style": true }]]
  }
```
- adding a `.babelrc` file
```json
{
  "plugins": [["import", { "libraryName": "antd", "style": true }]]
}
```

**Comment by rehandalal** [comment]
This appears to be fixed

**Comment by magopian** [comment]
I don't understand why, but indeed this isn't displaying in the test output anymore. Maybe updating a dependency fixed this at some point?
