### ISSUE TITLE
Add feature to sort and/or filter by actions to recipe listing

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#151]
Copied from: https://github.com/mozilla/normandy/issues/1040

> Being able to filter or sort by action type in the recipe listing can help quickly find the type of recipe that one cares about. It also stands out as the only default column that can't be sorted or filtered.

**Comment by mythmon** [comment]
I do a lot of querying the Normandy API, and one of the reasons I use the API directly instead of Delivery Console is because the API allows filtering by action type, and DC doesn't.

**Comment by peterbe** [comment]
Do you have a preference for that UI? It's very likely that @rehandalal already has a solution in mind. 
Personally, I'm a huge fan of using the text input with special keys like `something action:console-log action:preference` would make a DB query like `recipe.name ILIKE 'something' AND (actions.name = 'console-log' OR actions.name = 'preference')`

Power users would learn to type these in and it's possible to make cool autocomplete suggestions appear based on what you've last typed. I do something like this in my personal admin ui for my blog:
<img width="1152" alt="screen shot 2018-10-03 at 4 38 29 pm" src="https://user-images.githubusercontent.com/26739/46438045-e2a7c600-c72a-11e8-98cb-3704726b2534.png">

And, just like my little admin ui, if you click on any of the grey badges it basically does...
```javascript
this.setState({search: `${this.state.search} cat:${this.value}`})
```

Next to the "Columns" button we can have a button like "Show advanced filter options" or something which allows you to select from dropdowns and when you make some seletions there, it appends that to the free text string in a structured way.

**Comment by mythmon** [comment]
While I really love that sort of filtering UI, and would like to have that eventually, that isn't what I had in mind here. For one, I expect it would require a bunch of server changes, when this should be a purely UI change. I was thinking of just extending what we already have on Enabled:

![image](https://user-images.githubusercontent.com/305049/46440555-96538a80-c718-11e8-909e-ca4cb41227ba.png)

While it would be neat to making something whizbang flashy, I'd rather this just be a simple filter that uses existing search and filtering infrastructure we already have.

**Comment by peterbe** [comment]
For starters, to be able to sort by action we're going to need to land this: https://github.com/mozilla/normandy/issues/1573

**Comment by mythmon** [comment]
I'd say filtering (show me only preference rollouts) is much more useful that sorting. We can do both, but if sorting is going to take more than a few days, I'd like to get just filtering first, and defer sorting to another issue.

**Comment by peterbe** [comment]
Note that that PR, in normandy, didn't close this issue. That was just the data part of the filtering. 

I actually have a somewhat working version of filtering too. It works if I hardcode the list of action names but I need to take them from the redux store. 
Getting there.

**Comment by peterbe** [comment]
Work in progress!

<img width="1068" alt="screen shot 2018-10-05 at 3 36 02 pm" src="https://user-images.githubusercontent.com/26739/46556367-6e992980-c8b4-11e8-8f58-37c43d59f26b.png">

<img width="1041" alt="screen shot 2018-10-05 at 3 36 11 pm" src="https://user-images.githubusercontent.com/26739/46556378-78bb2800-c8b4-11e8-8979-7b505d5a81b2.png">

**Comment by peterbe** [comment]
For the record, this feature depends on a https://github.com/mozilla/normandy/commit/93b9cd62f8fb30fef9686ba823708326232bdc1d which, at the time of writing has only [made it to Dev](https://whatsdeployed.io/s-IwE).

So, as long as we make a Normandy release soon we'll be fine.
