### ISSUE TITLE
Handle refreshing the Auth0 token

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#155]
The Auth0 token is set to expire within 2 hours and we will need to figure out how to refresh the token.

**Comment by rehandalal** [comment]
As an initial stop gap solution:
- we should show the user a notification 15 minutes before the token is set to expire to let them know that they should refresh their token.
- if the user does not interact with the notification within the 15 minutes we do the refresh dance for them.

**Comment by mostlygeek** [comment]
Auth0 has a  [silent authentication](https://auth0.com/docs/api-auth/tutorials/silent-authentication) document for refreshing the access token. 

What about this: 

- have a setInterval that checks the token's TTL every 5 minutes
- if the token expiry is < 5 minutes we attempt a silent refresh in the background 
- if that *fails* then we show UX that they are logged out and need to refresh 

If the token is invalid or fails to refresh I'm OK with the Console redirecting people back to a login form.

**Comment by peterbe** [comment]
The word "silent" needs scrutiny and clarity.

*"To initiate a silent authentication request, add the prompt=none parameter when you redirect a user to the /authorize endpoint of Auth0's authentication API."* 

Can this be done in an XHR request? I'm guessing, if there's something wrong and the user needs to really be there, at the credentials prompt, you could do something like this:
```javascript
setInterval(() => {
  fetch('https://auth.mozilla.auth0.com/authrorize?a=b&prompt=none')
  .then(res => {
    if (res.status_code == 433) {
      // Oh no! We can't do this in the background. We need the users attention.
      alert("Hang on! You need to re-authenticate yourself. About to redirect you.")
      res.json().then(data => { window.location.href = data.auth_url })
    }
  })
}, 60 * 1000)
```
Anybody tried this?

**Comment by magopian** [comment]
Reposting here the content of an email from @peterbe 

```
Attention: People who do kinto or openid and stuff.

I've learned a lot today even though now in hindsight it all seems to simple and obvious.
In my Workon app [0] I use Kinto as the backend and openid bridge. 
It uses Kinto to auth and gets an accessToken into the browser (stores this in localStorage) which is
used on consecutive XHR requests (i.e. to sync the kinto.js).

Everything is working fine until the access token expires. Then you need to basically re-authenticate
with Auth0. Aka. Silent Authentication [1].
What I learned is that that can NOT be done with XHR requests. The only way to refresh the access
token is to literally redirect to Kinto's login URL (which redirects to Auth0).

The reason you can't use XHR Is because of CORS [2].
Instead of repeating that conclusion here, see this code comment:
https://github.com/peterbe/workon/blob/d956a523ea10905a1b3909cfeeecd380c403499e/src/OpenIDClient.js#L22-L40

So, with code grant auth flow, the user always has to be interrupted in whatever they're doing and
redirect out and back again. That kinda sucks. If you use implicit grant you can use auth0.js's "native"
solution which means it does the redirect spin in a hidden iframe. (Perhaps I can copy that!)

By the way, being able to do silent authentication with Kinto now depends on
https://github.com/Kinto/kinto/pull/1674
And I'm using this for one other trick; which is that when you load the page (after having been away
for more than 24 hours) it sniffs if you *had* a localStorage "expires_at" but that it was expired. In
that case it basically "clicks the Login button" for you but with the silent authentication flow.

Conclusion:
* Implicit grant looks attractive, but not sure if Kinto supports it. Gotto try that.
* Perhaps the silent authentication can be improved with a hidden iframe trick.
* It *is* possible to have session refresh (aka. silent authentication) with the Kinto OpenID stack
(pending PR merge plus release).

[0] https://github.com/peterbe/workon
[1] https://auth0.com/docs/api-auth/tutorials/silent-authentication
[2] https://fetch.spec.whatwg.org/#cors-protocol-and-credentials
```

**Comment by peterbe** [comment]
I have a working PR in the works. I've tested it exhaustively but discovered a problem...

When using my personal Auth0 account (which I use for workon.app which also uses implicit grant and `checkSession`) things work. But for the Mozilla Auth0 it's busted. Busted because of not matching "Allowed Web Origins" even though our setting is `https://normandy.dev.mozaws.net,http://localhost:3000,https://delivery-console.dev.mozaws.net/`. But if you change that to `http://localhost:3000,https://normandy.dev.mozaws.net,https://delivery-console.dev.mozaws.net/` (i.e. rearrange the order to make localhost:3000 first in the list) then things work. 

@gdestuynder believes there's a bug somewhere related to it only picking the first origin in that list. 

We can either set up a new Auth0 config dedicated for devs and one dedicated for Delivery Console Dev.

At this point, I have to defer this to kang.

**Comment by rehandalal** [comment]
I'm not opposed to setting up separate credentials for local development and the DC dev environment, but this also sounds like something we should report to Auth0.

**Comment by gdestuynder** [comment]
note, we fixed the web origin issue by just explicitly listing them all in auth0

**Comment by peterbe** [comment]
@gdestuynder I thought the "Allowed Web-origins" was set to list all 3 before, when it was breaking. And it was not until you rearranged the order that it started to work. Did I misunderstand that?

**Comment by gdestuynder** [comment]
it was empty (not set) which we though defaulted to all of the call back/ redirect URIs registered.
instead, it looks like it defaults only to the *first* redirect uri registered.

the fix was then to list of all of them

**Comment by peterbe** [comment]
Great news! In that case, I'm confident my [PR](https://github.com/mozilla/delivery-console/pull/233) is going to work for both Dev and local development. 

However, we have two more Auth0 configurations that need this change. Stage and Prod. Technically, for Normandy Stage and Normandy Prod, we need to make sure the "Allowed Web-Origins" *is set* to the same as the other URLs whatever they might be. 

Is it enough that I ask you here in this issue @gdestuynder or shall I file a Hub or a Bugzilla bug?

**Comment by gdestuynder** [comment]
@peterbe its done :)
