### ISSUE TITLE
Mozilla Auth0 credentials for dev

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#16]
We need to ask our Auth0 admins to set up credentials in Mozilla's Auth0 instance. 
All developers, who intend to hack on this locally, are going to need the credentials for the dev instance. 

This issue is about connecting this project to the request for credentials. 

This issue blocks: https://github.com/mozilla/delivery-console/issues/3

**Comment by peterbe** [comment]
Note-to-self: https://mozilla.service-now.com/sp?id=sc_request&table=sc_request&sys_id=d679539cdbf4df00809e17e15b96194a

**Comment by rehandalal** [comment]
Fixed by #157.
