### ISSUE TITLE
Allow editing bug number of recipes

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#165]
With mozilla/normandy#1392, Normandy now supports a bug number field to relate recipes with bugs. This field should be editable from Delivery Console, and should show in the detail page for a recipe.

**Comment by jaredkerim** [comment]
This will be deprecated in favour of storing the experimenter id (which therefore gets you all the relevant bugzilla ids)

https://github.com/mozilla/normandy/issues/1767
