### ISSUE TITLE
Set up Read the docs

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#17]
And link to it from the README

**Comment by peterbe** [comment]
Done. http://delivery-console.readthedocs.io/en/latest/

Now, we need to actually start populating it with some useful things like, for example, documentation. 

@rehandalal @andymikulski @magopian Please give me your usernames on readthedocs so I can add you as maintainers.

**Comment by rehandalal** [comment]
I'm `rehandalal`

**Comment by andymikulski** [comment]
`amikulski-moz`

**Comment by magopian** [comment]
Thanks for this work @peterbe 

I'm `magopian`

**Comment by peterbe** [comment]
All y'all added.
