### ISSUE TITLE
Add UI for Filter objects

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#176]
Normandy now supports specifying some filters in a structured JSON format, called Filter Objects (#1184).

Delivery console should have UI for these new filter types. The types currently provided by the UI are

* Version
* Channel
* Locale
* Country
* Bucket Sample
* Stable Sample

Docs for the above are here: http://normandy.readthedocs.io/en/stable/user/filters.html#module-normandy.recipes.filters

**Comment by mythmon** [comment]
Here is a previous iteration of this idea. The code was very different, but it can be treated as a wireframe to inspire the UI: https://github.com/mozilla/normandy/pull/987

**Comment by rehandalal** [comment]
For the record, I hate the UI from that linked PR. It's bulky and IMO harder to read than the filter expressions. 

I'll try and sketch up my ideas for this.

**Comment by peterbe** [comment]
> I'll try and sketch up my ideas for this.

Did you have something there to show?

**Comment by peterbe** [comment]
Taking over assignment after having chatted to @mostlygeek

**Comment by mythmon** [comment]
This is something that is becoming increasingly vital, as more people are writing and reviewing recipes. It will help prevent typos and other human errors, which helps us more confidently move more quickly.

**Comment by rehandalal** [comment]
![image](https://user-images.githubusercontent.com/987136/45228525-620fba00-b291-11e8-879c-33a6677f9136.png)

**Comment by rehandalal** [comment]
![image](https://user-images.githubusercontent.com/987136/45228548-7653b700-b291-11e8-81e7-40a40d965ecd.png)

**Comment by rehandalal** [comment]
![image](https://user-images.githubusercontent.com/987136/45228574-89668700-b291-11e8-8fd6-65821457b190.png)

**Comment by rehandalal** [comment]
![image](https://user-images.githubusercontent.com/987136/45228622-a438fb80-b291-11e8-963d-2a9ec49dee3d.png)

**Comment by peterbe** [comment]
Is it *always* just those three things? "Geo", "Browser" and "Sampling"?
Reason I ask is a tabbed layout like that could get very wide if we keep adding to it. 

Also, I'm guess an *extra* text input is to go below for that "extra_filter_expression". Right?

**Comment by mythmon** [comment]
The current available types of filter objects are available here: https://normandy.readthedocs.io/en/latest/user/filters.html. I encourage higher level abstractions on top of that, such as the Browser tab. More filters may be added in the future.

**Comment by peterbe** [comment]
> I encourage higher level abstractions on top of that, such as the Browser tab.

What do you mean?

**Comment by rehandalal** [comment]
> Is it always just those three things? "Geo", "Browser" and "Sampling"?

For now it is. Potentially this design will need to adapt when we have more groups.

**Comment by mythmon** [comment]
By high lever abstractions, I mean that the UI does not need to exactly match the schema of the filter objects, but should focus on providing nice interfaces for common tasks. For example, it would make sense to use a drop down for the bucket sample inputs to select common values, instead of a raw text field. Users can always fall back on writing filter expressions directly if needed for advanced things.

**Comment by peterbe** [comment]
I think what you're saying, in general, is that the UI/widgets need to just cover most of the common things. And that it *possible* to *write* a filter expression if something needs to go beyond what's available as drop-downs. 

I suspect that that means that any widget input needs to be optional. If you, for some reason, don't like the "Country" drop-down choices you should be able to skip and that type your own `country` thing to the extra_filter_expression.

**Comment by mythmon** [comment]
> I suspect that that means that any widget input needs to be optional. If you, for some reason, don't like the "Country" drop-down choices you should be able to skip and that type your own country thing to the extra_filter_expression.

This is very important. Most recipes will not use all of the filters available. For example country filters are relatively uncommon. One concern I have with the current mock up is that it isn't clear which filters are active on the recipe, and which are just "dormant" sitting in the UI but not doing anything.

**Comment by rehandalal** [comment]
> I suspect that that means that any widget input needs to be optional

Yes, all the filters should be optional

**Comment by peterbe** [comment]
Note-to-self; https://github.com/mozilla/normandy/issues/1544 is about making it impossible to store junk in the filter object fields for channels, countries, and locales. That should probably block this work.

**Comment by peterbe** [comment]
Any objections to closing this issue?

**Comment by mythmon** [comment]
I think this probably should have been fixed with 47f5187. I think the notation `fixes mozilla#176` confused the auto closer, and `fixes #176` would have worked.
