### ISSUE TITLE
Named Routes

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#20]
React-router does not currently support relative route links. It is preferable, though, that nested console apps _don't_ know what 'base path' they live under. For instance, Normandy should not care if it is hosted at `/normandy/` or `/` or `/shield/`, etc. This is undesirable primarily for the fact that if the prefix changes all the hardcoded URLs now must be updated, which becomes quite messy (especially when taking into account other console apps linking to each other).

An idea explored on Normandy is the idea of `named routes` which essentially assigns a string ID to each route, which the developer can then use to lookup later in the code. Here is a _very_ simple example of the concept:

```
// routes.js
{
  ...
  'normandy:recipes:home': '/normandy/recipe/',
  'normandy:recipes:listing:latest': '/normandy/recipe/listing?filter=latest',
  ...
}

// someComponent.js
...
<Link to={routes['normandy:recipes:home']}>Normandy recipe home</Link>
<Link to={routes['normandy:recipes:listing:latest']}>Normandy latest recipes</Link>
...

```

This approach solves some of our needs:
  - Devs don't need to know the routes of 'external' apps. If a path changes from one URL to another, nothing in the code needs to change outside this file.
  - Things such as handling the 'base path prefix' (`/normandy/` etc) can be abstracted away from the actual apps themselves, shielding devs from caring about the current route prefix when writing Links.
   - We _might_ be able to enforce Flow checking when writing Links, so devs don't point links to routes that don't exist. (I know we could do this using `enum`s in TypeScript, I'm not totally sure if Flow offers the same feature.)

The potential downsides sort of come down to implementation details. I'm imagining each app can simply have a `routes.js` which can be conglomerated into one 'master route collection', e.g.:

```
// normandy/routes.js
{
  'recipes': '/recipes'
}
// dashboard/routes.js
{
   'neat': '/neat-dashboards'
}

// ./routes.js imports and groups the subapp routes into:
{
  'normandy:recipes': '/normandy/recipes',
  'dashboard:neat': '/dashboard/neat-dashboards',
}
```

I think this should be a flexible approach that solves our needs and is _geeenerally_ future proof.

**Comment by magopian** [comment]
This looks like a very good idea!
In flow, I believe you'd use [union types](https://flow.org/en/docs/types/unions/)

**Comment by andymikulski** [comment]
Blocked by #118

**Comment by rehandalal** [comment]
Actually I think named routes are still a good idea so I'm reopening

**Comment by peterbe** [comment]
I have a good work-in-progress branch for this.

**Comment by rehandalal** [comment]
> I have a good work-in-progress branch for this.

is it based off my router improvements branch (#237)? because that will affect this.

**Comment by peterbe** [comment]
Oh noes!! I totally missed that. 2-3 hours wasted. 
I'm glad you made that last comment since my branch isn't finished or I would have spent even more time on it.
