### ISSUE TITLE
`onRowClick` is deprecated in favor of `onRow`

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#201]
`Warning: onRowClick is deprecated, please use onRow instead.`

**Comment by MrMuhammadRizwan** [comment]
**If you still getting this issue : Warning: onRowClick is deprecated, please use onRow instead.**
you can fixed this issue by trying this:
```
onRow={(record) => ({ onClick: () => { this.someClick(record.key) } })}
```
