### ISSUE TITLE
Can't manually remove the error messages

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#203]
When there's an error message displayed at the top of the page, it's not possible to manually remove it (it seems to disappear automatically after some time?).

Eg: going to [the new recipe page](http://localhost:3000/recipe/new/) and pressing the `save` button with an invalid form displays

<img width="537" alt="screen shot 2018-06-19 at 09 40 05" src="https://user-images.githubusercontent.com/167767/41583507-0632f02e-73a5-11e8-8b31-d43131e0c51a.png">

It would make sense to be able to click it to close it (or have a shorter timer for it to disappear automatically?)

Refs #186

**Comment by peterbe** [comment]
I saw that too! Then I looked up [the documentation](https://ant.design/components/message/) and slowly realized that that little red circle with a cross in it isn't a clickable thing but an icon. 

One solution would be to switch not [Notification](https://ant.design/components/notification/) instead which has a built-in closing functionality.
