### ISSUE TITLE
Refreshing the page logs the user out

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#204]
STR:
- login
- refresh the page

The login button shows `Log In`, and there's an error message displayed in the console:
`Error: [object Object]` which is located in `auth0.js` on line 35 (error while fetching the user info).

Refs #186

**Comment by rehandalal** [comment]
Weird, I didn't have this issue.

**Comment by magopian** [comment]
It doesn't seem to be reproducible every time, I'll investigate and see if there's a clearer STR

**Comment by magopian** [comment]
Well, can't reproduce it at all now. Closing.

**Comment by rehandalal** [comment]
I think I ran into this and it was due to an expired token still in localStorage. This would be fixed by #155. So I'll leave this closed.
