### ISSUE TITLE
Search recipes causes error

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#211]
STR:

* Go to http://localhost:3000/recipe/
* Type something into the search bar
* Hit Enter

`props.location is undefined`
<img width="1548" alt="screen shot 2018-06-19 at 2 49 09 pm" src="https://user-images.githubusercontent.com/26739/41618005-fa60c106-73cf-11e8-8aaa-c08742836d72.png">

**Comment by rehandalal** [comment]
This same issue appears to be affecting sorting and filtering.

**Comment by magopian** [comment]
Has this been fixed by #237 ? I tried reproducing locally on this branch, and couldn't, so I guess it's fixed there?

**Comment by rehandalal** [comment]
Yes #237 fixes this.
