### ISSUE TITLE
Unneeded packages

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#23]
I see lots of packages in `package.json` that we don't import. 
E.g. [localforage](https://github.com/mozilla/delivery-console/blob/ebc2628d47a68dc7c243e77ec1ae105810c7f1e5/package.json#L10), `react-copy-to-clipboard` and `underscore`.

**Comment by andymikulski** [comment]
These are present in Normandy, those packages made it in when I was first trying to import Normandy into the project and I must have forgot to remove it in the first PR.

They can be removed, but Normandy will ultimately need them later. Unless, of course, we want to make a point of writing those packages out of Normandy.

**Comment by peterbe** [comment]
Makes sense. But seriously, `localforage`?? `undercore`?? ;)

Do as you please but just don't forget. Also, it might be a good chance to "start" fresh and add them as you encounter them missing.

**Comment by andymikulski** [comment]
`localforage` was removed from normandy with the landing of #31

**Comment by peterbe** [comment]
I wish there was a tool like Pyup or Renovate that maps package names to module names (e.g. python-decouple on pypi is called decouple in python) and greps for these within the code. Probably is something. I know I wrote a quick script once. Then you could run that periodically to see if you've specified a package that you never use *directly*.
