### ISSUE TITLE
Wider margins for text fields

### ISSUE THREAD

**Issue by jtg567** [mozilla/delivery-console#270]
This is probably a pending "aesthetic improvement"

I counted 50 characters for one full line I found (assuming an equally spaced font for the filter expression box)

I think 150 char would leave us with less awkward line breaks and more readable filter expressions

**Comment by rehandalal** [comment]
Are you referring to the input for the filter expression on the create/edit page?

Or is this regarding the recipe details page?

**Comment by jtg567** [comment]
I had only encountered an old recipe on the details page when I opened this.

Now I see the create/edit page and I think Tyler mentioned the one line box on your email thread.

**Comment by jtg567** [comment]
Related to this issue... The following disconnect throws me off:

what I see at https://delivery-console.prod.mozaws.net/recipe/529/edit/
![image](https://user-images.githubusercontent.com/1797418/43419719-9785d55c-93f6-11e8-86da-2a81213ede26.png)

what I get at https://delivery-console.prod.mozaws.net/recipe/529/
![image](https://user-images.githubusercontent.com/1797418/43419679-7c43f878-93f6-11e8-85db-42982a9288af.png)
