### ISSUE TITLE
Publish a JSON version object

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#278]
From [Dockerflow guidelines](https://github.com/mozilla-services/Dockerflow#containerized-app-requirements):
> Must have a [JSON version object](https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md) at `/app/version.json`.

**Comment by rehandalal** [comment]
@sciurus I guess this should happen during the Jenkins build.

**Comment by sciurus** [comment]
I think your build scripts should generate this. Then jenkins can just continue building and uploading the app as normal. For example, see how themer does it:

https://github.com/mozilla/FirefoxColor/blob/b9d8824cef3a196bb7b774881fa61c6451e99676/webpack.web.js#L27-L30
https://github.com/mozilla/FirefoxColor/blob/b9d8824cef3a196bb7b774881fa61c6451e99676/webpack.web.js#L49-L57
