### ISSUE TITLE
Implement Architecture / Framework for Workflow based UX

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/delivery-console#292]
The current v1 of the DC was to set up our core tech tools (react, router, etc) and to port over the Normandy-Admin UI components. 

This issue sets us up for the second stage which is to transition to a workflow based user experience.  From 1:1 with @rehandalal we determined that this will require tweaking the plumbing and coming up with a new design.  

This issue is a place holder to track that foundation work: 

- [ ] with 
- [ ] some
- [ ] tasks 

... or if it is large enough we will close this issue and create a Project.

**Comment by rehandalal** [comment]
#410
