### ISSUE TITLE
Stray textbox on edit recipe page

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#293]
I saw this on dev:

![screenshot_2018-07-09 edit recipe delivery console](https://user-images.githubusercontent.com/305049/42467943-3e13d184-8368-11e8-8d2b-1af26198525b.png)

This textbox is a direct child of `<body>`, and has no identifying attributes, so I'm not sure where it came from.

**Comment by rehandalal** [comment]
I was able to track this down:
https://github.com/andreypopp/react-textarea-autosize/blob/2051b033ba3cf08faae73ae2113b07104f2e935e/src/calculateNodeHeight.js

This textbox is hidden locally by inline styles but CSP on the other environments causes the inline styles to fail and we see the textbox.

This is used for the autosize textareas so getting rid of autosize should fix the issue for now and I'll file an issue with antd to stop the weird hacky way in which they're doing this.
