### ISSUE TITLE
Add sentry policy to docs

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#294]
From https://github.com/mozilla/delivery-console/pull/277#issuecomment-403044919https://github.com/mozilla/delivery-console/pull/277#issuecomment-403044919:
> Actually, one thing I'd love to see in writing is a policy about Sentry errors. I'm not sure where it should go but it would be nice to have something formally written that like:
>
> > Every warning or error sent to Sentry has to be dealt with. If it's a new warning or error, at least it has to have a comment that points to a GitHub issue whose intent is to avoid it happening again.

**Comment by mythmon** [comment]
Our sentry instance has a way to link GH issues directly. We should do that instead of leaving them in comments.
