### ISSUE TITLE
Implement Auth0 workflow

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#3]
The application should be able to log in to Auth0 and acquire a JWT token to be passed over to other services.

Some guidelines: https://infosec.mozilla.org/guidelines/iam/openid_connect.html#authorization-code-grant

**Comment by magopian** [comment]
I don't see a global redux store yet, I was thinking about implementing the code very basically using the local state for now, and then maybe we'll switch that to using redux+sagas later on.

@rehandalal @andymikulski do you see any objection? I've created #36 to talk about how we want to use redux+sagas in the delivery-console, and we could work on that first, and then only move to fixing this issue.
