### ISSUE TITLE
Implement Changes from Rapid Risk Assessment Security Review

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/delivery-console#33]
See:  https://github.com/mozilla-services/foxsec/issues/825

**Comment by peterbe** [comment]
What does RRA mean?

**Comment by mostlygeek** [comment]
RRA = [Rapid Risk Analysis](https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment)

**Comment by rehandalal** [comment]
@mostlygeek that issue you linked to is private. is this something we should keep open? or can we close this for now and reopen when there are more details?

**Comment by mostlygeek** [comment]
We will implement issues coming out of the RRA as separate issues.  Closing this one.
