### ISSUE TITLE
Implement ESLint

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#34]
- [ ] Add `eslint` to project
- [ ] Add [Airbnb eslint config](https://www.npmjs.com/package/eslint-config-airbnb)
- [ ] Add `prettier-eslint`, change package.json scripts accordingly
- [ ] Ensure the CI process properly lints

Following discussion had in #32 !

**Comment by peterbe** [comment]
Why not use the eslint that we already get for free (with zero config!) in `create-react-app`? As far as I know we're checking in CI too that no warnings have been left in the code.
