### ISSUE TITLE
Implement a global store

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#36]
I believe that's what we decided on using, but we haven't implemented it in the delivery-console yet.

I've seen various ways to implement and use redux and sagas:
1/ one redux store per "meta component" (one for the console itself, one per "app"), or one global for the whole repository (with sub-objects for each app)
2/ pass the `store.dispatch` function everywhere so each component can fire "actions", or use action creators to "limit" what a component can do
3/ use the distinction between presentational and container components (see https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) or not care about it that much

Thoughts @rehandalal @andymikulski ?

**Comment by rehandalal** [comment]
We will be using thunks instead of sagas
