### ISSUE TITLE
Use virtual env

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#40]
We recently ran into an issue where different Node versions caused an error when running a PR locally. To avoid this in the future, I suggest we use something like [nodeenv](https://github.com/ekalinin/nodeenv):

```
> nodeenv --node=9.10.1 --prebuilt env
> . env/bin/activate
(env)> yarn
(env)> yarn start
```

We could include this as a script in package.json for first-time setup. There are other things like nodeenv such as [NVM](https://github.com/creationix/nvm), but I like nodeenv's operational similarity to virtualenv.

**Comment by rehandalal** [comment]
I think this solved by documenting requirements rather than enforcing a solution
