### ISSUE TITLE
Transition to Normandy V3 API

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#401]
We currently use the v2 API for everything. This is blocking deprecation of the v2 API and does not allow us to take advantage of improving features.

**Comment by mythmon** [comment]
This should wait until mozilla/normandy#1550 has landed, since it changes the shape of the v3 API quite a bit.

**Comment by peterbe** [comment]
https://github.com/mozilla/normandy/pull/1550 has landed. Yay! Let's start killing the use of v2 in delivery-console.

**Comment by peterbe** [comment]
Can we close this now?

**Comment by rehandalal** [comment]
Closed by #638
