### ISSUE TITLE
Save and continue button on recipe editor

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#43]
Copied from: https://github.com/mozilla/normandy/issues/1109

> Currently we have a single "Save" button. When you click this button it saves the changes you have made and flashes a message to let you know it has saved successfully.
> 
> I would like to change the behavior so that, when you click the "Save" button, it takes you back to the recipe details page after it successfully saves your changes.
> 
> In addition we should add a "Save and Continue" button that works the way the current "Save" button works.

**Comment by rohit114** [comment]
can i work on it?

**Comment by rehandalal** [comment]
> can i work on it?

absolutely!
