### ISSUE TITLE
Hide approval request buttons if viewing your own approval request

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#46]
Copied from: https://github.com/mozilla/normandy/issues/1034

> If I submit an approval request and then view the request history, I can still see the UI for commenting and approving/rejecting the request even though it's not possible for me to do those actions. It'd probably be good for us to hide everything except the close button when viewing your own approval request (unless `PEER_APPROVAL_ENFORCED` is false, of course).

**Comment by peterbe** [comment]
One potentially simple way to solve this is [here](https://github.com/mozilla/delivery-console/blob/9e223e207b33bd5e4fd2b0b925ab99118852188e/src/workflows/recipes/components/ApprovalRequest.js#L122-L123). We have the `userProfile` and we have the `approvalRequest`. So you *could* do this:

```javascript
if (userProfile) {
  if (userProfile.get('email') === approvalRequest.getIn(['creator', 'email'])) {
    detailSection = (
      <p>Can't approve your <i>own</i> requests.</p>
    );
  } else {
    detailSection = (
      <ApprovalForm
        approvalRequest={approvalRequest}
        isSubmitting={isSubmitting}
        onSubmit={this.handleSubmit}
        errors={errors}
      />
    );
} else {
```

But! How does the DC front-end know how the server is configured? I.e. whether `settings.PEER_APPROVAL_ENFORCED` is true or false. Does DC have an infra for getting server coonfigs from Normandy? We *could* perhaps insert this type of information into the `/api/v3/recipe/000/` API.

**Comment by rehandalal** [comment]
There is the service info endpoint where this kind of info should be exposed.

**Comment by mythmon** [comment]
Technically, we have endpoint that includes this information already: `/api/v3/service_info/

In practice, that seems to be broken. I've filed https://github.com/mozilla/normandy/issues/1747 for that.
