### ISSUE TITLE
Current-revision "markers" look broken/missing

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#479]
It looks like something is missing:

<img width="201" alt="screen shot 2018-09-27 at 2 19 08 pm" src="https://user-images.githubusercontent.com/26739/46166092-56942b00-c260-11e8-863c-e4757b5678e3.png">

<img width="150" alt="screen shot 2018-09-27 at 2 19 39 pm" src="https://user-images.githubusercontent.com/26739/46166128-67dd3780-c260-11e8-9b0f-bc306ccc5799.png">

**Comment by mythmon** [comment]
```
52c9037535a54d1dcc2a4fd9931c588bac9ef9cf is the first bad commit
commit 52c9037535a54d1dcc2a4fd9931c588bac9ef9cfAuthor: Renovate Bot <bot@renovateapp.com>
Date:   Mon Sep 3 11:55:38 2018 +0000

    Update dependency antd to v3.9.1

:100644 100644 057d4234a2202ad9e7e4dd5cf9b1627a991300a3 bd2ebcb2167a235fc3220acca969cd48e377ae4b M      package.json:100644 100644 42476a570736f4da2f2612da5eb9df0f8c695cf1 b83c7b013443755bd674f25957212266f36f7684 M      yarn.lock
```

**Comment by mythmon** [comment]
Reading [the PR for the antd upgrade](https://github.com/mozilla/delivery-console/pull/419), we went from 3.8.x to 3.9.1, and 3.9 introduced a lot of changes to icons, which makes it seem like a pretty direct cause of the above.
