### ISSUE TITLE
Implement deployment through Circle CI

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#5]
We should be able to create tags on the repo which should get built and deployed to the S3 bucket where delivery console will live.

**Comment by peterbe** [comment]
Warming up https://bugzilla.mozilla.org/show_bug.cgi?id=1442345

**Comment by peterbe** [comment]
Making progress. We have [these lines](https://github.com/mozilla/delivery-console/blob/a2644268e3d8913a7dd31cd682a876d6a579c869/.circleci/config.yml#L47-L52) in circle which will execute `./bin/deploy.sh`. 

[`bin/deploy.sh`](https://github.com/mozilla/delivery-console/blob/master/bin/deploy.sh) is currently a stub that doesn't do anything. The idea is that once we have a place to upload our build to, we do that from this script. The necessary credentials will go into [circle settings here](https://circleci.com/gh/mozilla/delivery-console/edit).

**Comment by rehandalal** [comment]
@milescrabill is gonna implement the shit out of this!

**Comment by milescrabill** [comment]
I have automated this via Jenkins, which polls this repo every minute to check for changes to the repo (via git ls-remote) and then:

- if there is a change to master, deploys dev
- if there is a new tag, deploys stage

the deploy process happens in the latest `node:8` container, see [here](https://github.com/mozilla-services/cloudops-deployment/blob/3c71f39640657cc9d02a0755fdf685045c881b93/projects/deliveryconsole/pipeline.groovy#L37-L65), then invalidates cloudfront's cache.

This prevents the need to have any kind of AWS credentials in CircleCI for this project. We don't need a deploy step in CI.
