### ISSUE TITLE
Error on extension detail page: c is null; can't access its "split" property

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#543]
https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/4882572/

This is probably a problem somewhere in [v5..v6](https://github.com/mozilla/delivery-console/compare/v5..v6). Prod (v5) works fine and Stage (v6) is broken.

```
TypeError: c is null; can't access its "split" property
```

**Comment by peterbe** [comment]
It's because of this https://github.com/mozilla/delivery-console/pull/540
