### ISSUE TITLE
"Disabled" recipes isn't the right word

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#572]
I just created a recipe. And immediately after editing I clicked "Approval Request". So it hasn't even been enabled yet. 

Yet it looks like this:
<img width="1075" alt="screen shot 2018-11-09 at 12 14 13 pm" src="https://user-images.githubusercontent.com/26739/48277658-4a7fb980-e419-11e8-9e9d-fa3b35194e1d.png">

There's got to be something better like. "Awaiting approval" or "Not enabled" or "Not applicable".

**Comment by peterbe** [comment]
The wording "Disabled" comes from https://github.com/mozilla/delivery-console/blob/b070dd761be78f33b4348cf5f2463baab1b3f06a/src/components/common/EnrollmentStatus.js#L17

It's the default wording if the recipe isn't enabled. (If it is enabled, it branches into other options). Perhaps, with the incoming v3 API we can look at the recipe `enabled_states` array perhaps to see if it was ever enabled.

**Comment by peterbe** [comment]
Blocked on https://github.com/mozilla/delivery-console/issues/575 mayhaps?

**Comment by mythmon** [comment]
Perhaps making the default wording "Not enabled" would be a good stop gap here? To me it implies better a lack of action. I feel like we might have more pressing issues to work on at the moment though.

**Comment by peterbe** [comment]
Yeah, "Not enabled" can encompass both "Disabled" *and* "Was never enabled". 

But I think it's worth holding out for the v3 API which will have that `enabled_states` and then we can *really* get it right.

**Comment by mythmon** [comment]
One issue is that currently, the enabled_states is only visible per revision, and the only way to see the entire state of the enabled states is to look at all the revisions of a recipe in its history. I think to do what you're proposing would currently require one request per recipe row on the detail page. That seems kind of slow. We'd definitely want to have some sort of smaller scope on the spinner for that too.

This isn't the first time where cheaply getting the entire enabled history would be useful, so maybe we can make the entire enabled state more visible in the API? That's an even bigger change though.

**Comment by peterbe** [comment]
Hehe. The stopgap solution looks more attractive now. 

A potentially tangential idea is to say something about the approval state if it's not enabled. E.g. "Not asked for approval", "Awaiting approval", "Approved". It *might* require rethinking the *name* of the column head.
