### ISSUE TITLE
UI for preference rollout

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#63]
Copied from: https://github.com/mozilla/normandy/issues/1197

> We'll need a UI to create preference rollout recipes. Note that this is going to be implemented as a "local action" in the normandy client. See [bug 1440782](https://bugzilla.mozilla.org/show_bug.cgi?id=1440782) for more info.
> 
> This will likely have to wait until the local action is speced out so we know what arguments will be needed
> 
> ### [Preference roll-out blueprint](https://docs.google.com/document/d/1qFCOscDiMGVDcBYtznzgPNCWzOhaxC4X5VGt3LTjZY0/edit#heading=h.eoqr3si0tn8z)

**Comment by mythmon** [comment]
The local action is fully specified now. The schema for arguments is available as a part of the [mozilla-normandy-action-argument-schemas](https://www.npmjs.com/package/mozilla-normandy-action-argument-schemas) package. The source for that package is [in mozilla-central](https://hg.mozilla.org/mozilla-central/file/tip/toolkit/components/normandy/actions/schemas/index.js#l18).

Note that there are actually two actions here: `preference-rollout` and `preference-rollback`.

**Comment by rehandalal** [comment]
@magopian have you begun work on this? if not i'll probably grab this.

**Comment by peterbe** [comment]
Taking over assignment after having chatted to @mostlygeek

**Comment by rehandalal** [comment]
UI on the left and generated JSON on the right:
![image](https://user-images.githubusercontent.com/987136/44500689-e2120f00-a657-11e8-8fc8-d91ba444f922.png)

**Comment by peterbe** [comment]
@rehandalal When viewing the recipe, should it display the JSON or should it display the details in some more regular table? 

I.e.
<img width="692" alt="screen shot 2018-08-28 at 1 45 01 pm" src="https://user-images.githubusercontent.com/26739/44740495-a00a2280-aac8-11e8-996e-dc0301bfa6e8.png">

**Comment by rehandalal** [comment]
It would definitely be nicer to show a table of data instead of JSON
