### ISSUE TITLE
UI for preference rollback

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#697]
In #63 we added UI for preference rollout, the forward action. We also need a UI for preference rollback, which is the reverse action.

The UI for this should offer a list of preference rollout recipes that don't already have rollbacks. If that rollout is active, it should show a warning (since the server requires that only one of the rollout and rollback are active).

**Comment by peterbe** [comment]
@mythmon Perhaps I can figure this out from the code but, is there only really one value that needs to be set and that being `{"rolloutSlug": VALUE}`?

**Comment by mythmon** [comment]
That's right. I updated the docs to include information about this action last week: https://normandy.readthedocs.io/user/actions/preference-rollback.html

It would be very cool if the value of `rolloutSlug` was something that could be autocompleted from the existing rollouts on the server, but that's probably more fancy than we need.

**Comment by peterbe** [comment]
> ...could be autocompleted from the existing rollouts on the server, but that's probably more fancy than we need

almost already there :)
<img width="1101" alt="screen shot 2019-02-06 at 2 36 57 pm" src="https://user-images.githubusercontent.com/26739/52368560-bd023480-2a1c-11e9-918a-88b218db56b2.png">
