### ISSUE TITLE
Current revision is wrongly displayed as the previous one when viewing an Approval Request

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#775]
Cloned from https://bugzilla.mozilla.org/show_bug.cgi?id=1527579
---

**[Affected versions]:**
- Firefox Nightly 67.0a1, Build ID 20190211215545

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have access to the [delivery console](http://delivery-console.stage.mozaws.net/).

**[Steps to reproduce]:**
1. Navigate to http://delivery-console.stage.mozaws.net/.
2. Set up any recipe.
3. Edit the previously created recipe.
4. Change/add something to the recipe. (eg. add/change the additional filter expression)
5. Save the changes and request approval.
6. Click the "Approval Request" button next to the recipe and observe the edited section.

**[Expected results]:**
- The changes made in Step 4 are reflected in the latest approval request.

**[Actual results]:**
- No changes can be observed when comparing with the previous approval request.

**[Notes]:**
- If a 3rd approval request is made after making some edits, the 1st revision will be displayed correctly while the current and previous ones will look the same.
- If you load revisions from the History section, all revisions are loaded and are displayed correctly.
- Attached a screen recording of the issue.

![current revision is dispalyed as previous one](https://user-images.githubusercontent.com/18304511/52776510-6911d400-304a-11e9-97b4-0fea0f6aa87b.gif)

**Comment by peterbe** [comment]
Probably due to the v3 switch @rehandalal ?

**Comment by rehandalal** [comment]
yeah it probably happened then. do you have bandwidth to explore? or i can take a look tomorrow

**Comment by rkothari19** [comment]
Mythmon and I also ran into this problem when dealing with https://bugzilla.mozilla.org/show_bug.cgi?id=1527748#c18. It can be quite confusing and misleading as it is !WYSIWYG

**Comment by rkothari19** [comment]
I ran into this problem again, an hour ago. Is this really fixed?
![screenshot_2019-03-02 recipe approval history 634 rollout monitor v2 bug 1505837 delivery console](https://user-images.githubusercontent.com/12902417/53675891-54d7f480-3c50-11e9-8f54-ead8922366be.png)

**Comment by rehandalal** [comment]
@rkothari19 it is fixed in master but the fix has not yet been deployed to stage/prod.

**Comment by rehandalal** [comment]
This should now be fixed on prod

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reproducible. Considering this I will mark the issue as verified fixed.
