### ISSUE TITLE
Pagination no longer working on the Recipe view in the Delivery Console

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#776]
Cloned from https://bugzilla.mozilla.org/show_bug.cgi?id=1527602
---

**[Affected versions]:**
- Firefox Nightly 67.0a1, Build ID 20190211215545

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have access to the [delivery console](http://delivery-console.stage.mozaws.net/).

**[Steps to reproduce]:**
1. Navigate to https://delivery-console.stage.mozaws.net/recipe/.
2. Scroll down the page and click the "2" page number.
3. Observe the behavior.

**[Expected results]:**
- The 2nd page of recipes is displayed.

**[Actual results]:**
- The page is refreshed and the URL is changed but the content remains the same.

**[Notes]:**
- The issue is reproducible for all 51 pages.
- The issue is not reproducible on the Extensions view.
- Attached a screen recording of the issue.

![pagination not working for recipes](https://user-images.githubusercontent.com/18304511/52776525-74fd9600-304a-11e9-9aa7-1119867073c3.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reproducible. Considering this I will mark the issue as verified fixed.
