### ISSUE TITLE
Pre-fill recipe creation form from URL fragment.

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#802]
To ease integration with Experimenter, Delivery Console should accept a JSON-encoded version of a recipe as initial data via the URL fragment. This data should be formatted in the same way that the Normandy API would expect as data to `POST /api/v3/recipe/`.

This should include anything that will be sent to Normandy, including filter objects, action type, and action arguments. Unrecognized fields should be shown to the user, in case they include data that needs to be translated into other fields. For example, experimenter might include a field like "experimenter-extra" where it puts notes from study owners such as additional filtering criteria.

The expectation here is that Experimenter can generate URLs that encode everything it knows about a recipe when we are trying to launch it. These URLs will be shown to the experiments operations team, which can then jump over to Delivery Console to create and launch a recipe. It should help eliminate copy-and-paste errors, and speed up recipe creation in a safe way.

One concern is that this could be a XHR attack vector. This is mitigated because Delivery Console is a purely front-end app, so the page must actually be rendered to do anything with the fragment. Additionally, this data is only used to pre-fill the form, and shouldn't automatically submit anything. This means the user has to interact with the form to actually make any changes. Further, this flow only exposes recipe creation, not the approval request process.

**Comment by mythmon** [comment]
It might also be useful to provide an import/export version of this feature. It could serialize the form to JSON and put it on the clipboard, or pull JSON from the clipboard and deserialize it into the form.

**Comment by peterbe** [comment]
Is this a bad time to add a new field to the Normandy RecipeRevision called something like `experimenter_id` or `experimenter_url`? That would be sweet to include with this pre-fill.

**Comment by mythmon** [comment]
> Is this a bad time to add a new field to the Normandy RecipeRevision called something like `experimenter_id` or `experimenter_url`? That would be sweet to include with this pre-fill.

I don't think it's a bad time, but I think we should put it in a separate issue. If only because this would be mostly a Normandy API change. Also, we should definitely use just a pk and not a URL. We've gotten in trouble by storing URLs already (mozilla/normandy#1567).

**Comment by peterbe** [comment]
See https://github.com/mozilla/delivery-console/issues/808

Also, @mythmon is there a reason you used the word "fragment" in this issue? Do you mean query string?

**Comment by mythmon** [comment]
By "fragment" I meant the fragment identifier, more commonly known as the URL's *hash*. This has the unique feature that it is never sent to servers, and handled entirely by the client. That helps me feel better about the security implications of this, since the network can't mess with it.
