### ISSUE TITLE
Expose experimenter_id

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#808]
As of https://github.com/mozilla/normandy/pull/1770 each recipe revision will have a new field. 
I suspect it's only ever relevant for certain action types so we could make presence of an input widget for this depend on that. But who knows, perhaps a preference-rollout could actually be related to an experiment. I dunno. 

Normandy will validate it as being a number. 

I see no reason to wait for https://github.com/mozilla/delivery-console/issues/802 to implement this. Right?

**Comment by mythmon** [comment]
> I see no reason to wait for #802 to implement this. Right?

:+1:
