### ISSUE TITLE
The "opt-out-study" recipes cannot be updated after they were created

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/delivery-console#824]
*[Notes]:*
- The recipes can be edited and saved only if you choose a different extension.

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

*[Affected Versions]:*
- Firefox Nightly 67.0a1

*[Prerequisites]:*
- Have access to the delivery console.

*[Steps to reproduce]:*
1. Navigate to http://delivery-console.stage.mozaws.net/.
2. Create an opt-out-study recipe.
3. Edit any field from the previously created recipe except the extension.
4. Click the "Save" button and observe the behavior.

*[Expected result]:*
- The changes are successfully saved.

*[Actual result]:*
- "Could not validate form. Please correct the form items highlighted below." error is displayed.

*[Additional Notes]:*
- The issue is reproducible even if the recipe is Disabled or Active.
- The issue is not reproducible for the "preference-experiment" recipes. 
- No items are highlighted even if the displayed error instructs you to correct them in order to save the updates.
- Attached a screen recording with the issue:
![edit opt out study](https://user-images.githubusercontent.com/19226534/53940765-2bd7b980-40bf-11e9-9f44-2d79d81bdfb6.gif)
k

**Comment by peterbe** [comment]
I poked but didn't get far. I can't upload extensions on my localhost version. I'm mention that in Normandy.

The pressing of the Save button causes the form validation error without XHR by the way.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reproducible. Considering this I will mark the issue as verified fixed.
