### ISSUE TITLE
Uploading extension could be easier

### ISSUE THREAD

**Issue by peterbe** [mozilla/delivery-console#830]
Why do I have to type in the name? Can't it be that file field widget first and onChange it extracts the filename and populates the Name field for me.
<img width="1192" alt="screen shot 2019-03-07 at 2 29 30 pm" src="https://user-images.githubusercontent.com/26739/53983557-71a77880-40e5-11e9-8219-7f6e4ff82847.png">

The "Extension (XPI)" lacks a "mandatory red star" even though, in fact, it is mandatory. 
<img width="1259" alt="screen shot 2019-03-07 at 2 29 57 pm" src="https://user-images.githubusercontent.com/26739/53983683-c5b25d00-40e5-11e9-930b-cb72055c5895.png">

**Comment by mythmon** [comment]
In usage, the name field can't really be generated from the XPI's metadata. The "name" field here is basically just a comment that people can note interesting information in regarding how the add-on is to be used. Check out the production data to see what I mean.

**Comment by peterbe** [comment]
> Check out the production data to see what I mean.

I see! I looked at Stage and there, from a quick glimpse, it looked like all names was the basename of the xpi file.
