### ISSUE TITLE
Editing recipes sometimes fails with no error message

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#852]
Lately, I've been noticing that editing a recipe fails sometimes. The UI says to fix the errors in the marked fields, but no fields are marked. This only happens when editing an existing recipe.

There aren't any useful logs or network errors. In fact, no network request is shown in the Firefox devtools.

**Comment by rehandalal** [comment]
Do you have any STR?

**Comment by mythmon** [comment]
All the times I've seen this so far, the STR are:

1. Create a recipe
2. Close the tab
3. Re-navigate to the recipe
4. Edit the recipe
5. Press save

Expected:

The recipe is updated

Actual:

The recipe is not updated, the error says to fix marked fields, no fields are marked.

I've seen this on both prod and stage, and so has Erica Wright (on stage). I haven't been able to reproduce it locally, and trying it again on stage worked fine.

**Comment by mythmon** [comment]
Another note: I'm exploring whether this is actually a Normandy configuration issue, which would explain why I couldn't make it happen in local development.

**Comment by mythmon** [comment]
Also, I was able to make an equivalent request using DC's authorization token from the command line.

**Comment by peterbe** [comment]
> exploring whether this is actually a Normandy configuration issue

But if you don't see any XHR, what's it got to do with Normandy?

**Comment by mythmon** [comment]
Some types of server configurations, especially related to CSP and CORS, cause requests to be aborted before they show up in the network panel, or even to never happen. For example, CSP can block XHR to other domains, and CORS will do a pre-flight HEAD request (which doesn't show in the network panel) that can cancel PATCH requests.

**Comment by jaredkerim** [comment]
Unable to reproduce
