### ISSUE TITLE
Allow for local authentication instead of auth0.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/delivery-console#854]
There should be a way that delivery-console can be authenticated locally without the need for auth0.

**Comment by mythmon** [comment]
See also mozilla/normandy#1807, where we will make Normandy understand simpler debugging authentication for development and QA.

**Comment by jrbenny35** [comment]
@mythmon Any updates on this? Just wondering how this fits into your goals and such.

**Comment by rehandalal** [comment]
https://github.com/mozilla/normandy/pull/1839 addresses the Normandy parts of this.

**Comment by rehandalal** [comment]
Fixed by #880
