### ISSUE TITLE
Test warnings

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#89]
In #86 , Normandy tests were converted from Karma/Jasmine to Jest/Enzyme. This in itself is fine, however the tests now spam console warnings while running:

<img src="https://user-images.githubusercontent.com/2767162/38382809-c1dc46de-38bf-11e8-96ac-68d3b504fbf5.png" />

These almost entirely stem from mismatched propTypes, but @magopian made a good point regarding the fact we may uncover bugs by fixing these warnings.

**Comment by peterbe** [comment]
I don't see these warnings any more when I run `yarn run test:jest`. Is there a thing to enable warnings that I'm missing out on? @rehandalal @magopian 

Or, is this a thing of the past?

**Comment by rehandalal** [comment]
I still see them running: `yarn run test`

**Comment by magopian** [comment]
It's weird, I don't see them either...

**Comment by magopian** [comment]
oh, sorry, I closed, but if @rehandalal can still see them... it would make sense to investigate why he sees them and not us... and then maybe fix those warnings ;)
