### ISSUE TITLE
The experiment name error message is displayed even though the characters that were used are found in the symbol list

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#937]
**[Affected versions]:**
- Firefox Release 67.0.3, Build ID 20190618025334
- Firefox Beta 68.0b11, Build ID 20190617172838
- Firefox Nightly  69.0a1, Build ID 20190613215335

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net.
2. Create a new preference experiment or rollout and fill out all fields except the slug with valid strings/options.
3. In the Experiment Name or Slug field write a string with a special character that can be found in the following interval: `^[A-Za-z0-9\\-_]+$` for pref experiments or `^[a-z0-9\\-_]+$` for rollouts.
4. Save the recipe and observe the behavior.

**[Expected results]:**
- The recipe is saved.

**[Actual results]:**
- the `does not match '^[A-Za-z0-9\\-_]+$'` error is displayed even though all characters that were used appear to have been valid.

**[Notes]:**
- The issue is not reproducible for add-on experiments. But it looks like there is no restriction for what can be used as Study Names in this case.
- Attached a screenshot of the issue.
![image](https://user-images.githubusercontent.com/18304511/59850995-2ce1dd80-9374-11e9-91a8-cf831967ef2a.png)

**Comment by mythmon** [comment]
`^[A-Za-z0-9\\-_]+$` is a regex that means "a string consisting entirely of capital or lower case letters, digits, hyphens or underscores, repeated one or more times". the `+` symbol is "repeated one or more times". It does not mean that `+` is a valid character in the input. This is working as expected.

**Comment by SoftVision-CiprianMuresan** [comment]
Oh, sorry for the noise then. But shouldn't opt-out experiments be subject to the same constraint when choosing a study name?

**Comment by mythmon** [comment]
In a perfect world yes, but for historical reasons we can't put that restriction on opt-out experiments. The next-gen version of add-on studies will have a more coherent system.
