### ISSUE TITLE
Backend is not working on starting using "npm start"

### ISSUE THREAD

**Issue by Rupeshiya** [mozilla/delivery-console#978]
Getting this in console :
```
request.js:1 GET https://localhost:8000/api/v3/action/ net::ERR_CONNECTION_REFUSED
```
for all the server request sent from client-side

**Comment by rehandalal** [comment]
Thanks for filing an issue. We should do a better job surfacing this information but you need to be running a local instance of [Normandy](https://github.com/mozilla/normandy/) (which would typically be at `https://localhost:8000`.

**Comment by Rupeshiya** [comment]
thanks for providing info @rehandalal  , will try Normandy

**Comment by rehandalal** [comment]
I should also mention we are in the process of sunsetting this project and so if you are looking to contribute to a project this may not be the best one. But Mozilla has plenty of other projects that would welcome contributions and I'd be happy to help you find a better one.

**Comment by Rupeshiya** [comment]
Great, thanks @rehandalal . Please let me know some web related projects.

**Comment by rehandalal** [comment]
These are probably two good options with strong contributor support:
MDN: https://github.com/mozilla/kuma
SuMo: https://github.com/mozilla/kitsune
