### ISSUE TITLE
Several fields are scrambled on the recipe "Details" page from the Delivery Console

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/delivery-console#981]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Beta 69.0b10, Build ID 20190801185445

[Prerequisites]:
- Have access to the Delivery Console.

[Steps to reproduce]:
1. Open the browser.
2. Navigate to https://delivery-console.stage.mozaws.net/
3. Click the "Recipes" button and click on one of the recipes.
4. Observe the page.

[Expected result]:
- All fields are correctly displayed.

[Actual result]:
- Several fields have their strings duplicated and are misaligned with their values.

[Notes]:
- All recipes types are affected by this issue.
- All the fields below the "Action Name" field are affected.
- The Slugs and Branches values are displayed with a horizontal scrollbar.
- All fields are correctly displayed when creating a new recipe or editing an existing one.
- This issue is only reproducible on the stage version of the Delivery Console.
- I have attached a screenshot of the issue:
![DC_misaligned_fields](https://user-images.githubusercontent.com/40393891/62466097-2929df00-b799-11e9-8d27-746f01007028.png)

**Comment by mythmon** [comment]
Using `git bisect`, I narrowed this down to being caused by #950.

**Comment by rehandalal** [comment]
Thanks for tracking that down. It's weird that was what caused it but I'll figure it out and get this fixed.

**Comment by rehandalal** [comment]
Turns out this issue is actually a result of https://github.com/immutable-js/immutable-js/releases/tag/v4.0.0-rc.5.

Should be an easy fix.
