### ISSUE TITLE
No recipes are displayed when opening the "Recipes" page for the first time

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/delivery-console#986]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Beta 69.0b11, Build ID 20190805120428

[Prerequisites]:
- Have access to the Delivery Console.

[Steps to reproduce]:
1. Open the browser.
2. Navigate to https://delivery-console.stage.mozaws.net/
3. Click the "Recipes" button and observe the page.

[Expected result]:
- The page is populated with recipes.

[Actual result]:
- No recipes are displayed and a "No Data" string is displayed.

[Notes]:
- Workaround: Clicking one of the filters populates the page.
- I have attached a screenshot of the issue:
![DC_no_recipes](https://user-images.githubusercontent.com/40393891/62623313-34137980-b929-11e9-8fe0-4fde74ccda19.png)

**Comment by Softvision-PatriciuPop** [comment]
After additional testing it appears that this behavior is reproducible on pages 1, 29, and above. 
And navigating from any page to the first doesn't change the recipes listed on the page. 
It looks like only pages from 2 to 28 update the recipes displayed when navigating to them.

Also, if you try to navigate to the affected pages by changing the page number from the address bar you are prompted with the "No Data" string.

**Comment by rehandalal** [comment]
This issue appears to only be on stage. I cannot reproduce locally. I have seen a Sentry error that appears to be related:
https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/6123554/

**Comment by rehandalal** [comment]
This issue appears to be caused by bad data on Normandy server. @mythmon is cleaning out the bad recipes and that should fix this issue.
