### ISSUE TITLE
The "Name", "Action", "Enabled", and "Last Updated" filters from the "Recipes" page no longer work correctly

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/delivery-console#987]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Beta 69.0b11, Build ID 20190805120428

[Prerequisites]:
- Have access to the Delivery Console.

[Steps to reproduce]:
1. Open the browser.
2. Navigate to https://delivery-console.stage.mozaws.net/
3. Click the "Recipes" button and click on the "Name" filter.
4. Click on the "Name" filter again and observe the behavior.

[Expected result]:
- The recipes are displayed in reverse order.

[Actual result]:
- The order of the recipes is not changed.

[Notes]:
- Reverse ordering no longer works for the following filters: "Name", "Action", "Enabled", and "Last Updated".
- Filters work correctly only when the "Enabled" filter is set to "enabled".
- Changing the "Enabled" filter from "enabled" to "disabled" does not update the list.
- I have attached a screen recording of the issue:
![DC_filters](https://user-images.githubusercontent.com/40393891/62628999-03d1d800-b935-11e9-958b-d96939d37338.gif)

**Comment by rehandalal** [comment]
This issue appears to be caused by bad data on Normandy server. @mythmon is cleaning out the bad recipes and that should fix this issue.
